// Subtle provenance label: 🤖 Proposed for machine-generated content,
// ✓ Verified for human-confirmed, Synced for system-applied writes.

export default function ProvenanceBadge({ source }: { source?: string }) {
  if (!source) return null;
  const s = source.toLowerCase();
  if (s.includes('ai-generated') || s.includes('proposed')) {
    return (
      <span
        title="Generated by Sanchalan — not yet human-verified"
        className="inline-flex shrink-0 items-center rounded bg-[#EFEFEA] px-1.5 py-0.5 text-[11px] font-medium text-[#6B6B6B] ring-1 ring-inset ring-[#E8E8E6]"
      >
        🤖 Proposed
      </span>
    );
  }
  if (s.includes('verified')) {
    return (
      <span
        title="Human-verified"
        className="inline-flex shrink-0 items-center rounded bg-green-50 px-1.5 py-0.5 text-[11px] font-medium text-green-700 ring-1 ring-inset ring-green-200"
      >
        ✓ Verified
      </span>
    );
  }
  if (s.includes('synced')) {
    return (
      <span className="inline-flex shrink-0 items-center rounded bg-blue-50 px-1.5 py-0.5 text-[11px] font-medium text-blue-700 ring-1 ring-inset ring-blue-200">
        Synced
      </span>
    );
  }
  return (
    <span className="inline-flex shrink-0 items-center rounded bg-[#EFEFEA] px-1.5 py-0.5 text-[11px] font-medium text-[#6B6B6B] ring-1 ring-inset ring-[#E8E8E6]">
      {source}
    </span>
  );
}
